Number of stores not made persistent: 0

Number of redundantly flushed stores: 1
Stores flushed multiple times:
[0]    at 0x........: main (flush_check.c:28)
	Address: 0x........	size: 8	state: FLUSHED

Number of unnecessary flushes: 2
[0]    at 0x........: main (flush_check.c:34)
	Address: 0x........	size: 128
[1]    at 0x........: main (flush_check.c:36)
	Address: 0x........	size: 128
ERROR SUMMARY: 3 errors
