Number of stores not made persistent: 4
Stores not made persistent properly:
[0]    at 0x........: main (const_store.c:31)
	Address: 0x........	size: 1	state: DIRTY
[1]    at 0x........: main (const_store.c:32)
	Address: 0x........	size: 2	state: DIRTY
[2]    at 0x........: main (const_store.c:33)
	Address: 0x........	size: 4	state: DIRTY
[3]    at 0x........: main (const_store.c:34)
	Address: 0x........	size: 8	state: DIRTY
Total memory not made persistent: 15
ERROR SUMMARY: 4 errors
