Number of stores not made persistent: 1
Stores not made persistent properly:
[0]    at 0x........: main (flush_check.c:27)
	Address: 0x........	size: 8	state: COMMITTED
Total memory not made persistent: 8

Number of redundantly flushed stores: 3
Stores flushed multiple times:
[0]    at 0x........: main (flush_check.c:27)
	Address: 0x........	size: 8	state: FLUSHED
[1]    at 0x........: main (flush_check.c:27)
	Address: 0x........	size: 8	state: FENCED
[2]    at 0x........: main (flush_check.c:27)
	Address: 0x........	size: 8	state: COMMITTED
ERROR SUMMARY: 4 errors
