Number of stores not made persistent: 2
Stores not made persistent properly:
[0]    at 0x........: main (isa_check.c:50)
	Address: 0x........	size: 8	state: COMMITTED
[1]    at 0x........: main (isa_check.c:57)
	Address: 0x........	size: 8	state: FLUSHED
Total memory not made persistent: 16

Number of redundantly flushed stores: 5
Stores flushed multiple times:
[0]    at 0x........: main (isa_check.c:37)
	Address: 0x........	size: 8	state: FENCED
[1]    at 0x........: main (isa_check.c:37)
	Address: 0x........	size: 8	state: FENCED
[2]    at 0x........: main (isa_check.c:37)
	Address: 0x........	size: 8	state: COMMITTED
[3]    at 0x........: main (isa_check.c:50)
	Address: 0x........	size: 8	state: FLUSHED
[4]    at 0x........: main (isa_check.c:57)
	Address: 0x........	size: 8	state: FLUSHED
ERROR SUMMARY: 7 errors
