Number of stores not made persistent: 1
Stores not made persistent properly:
[0]    at 0x........: main (isa_check.c:50)
	Address: 0x........	size: 8	state: FLUSHED
Total memory not made persistent: 8

Number of redundantly flushed stores: 2
Stores flushed multiple times:
[0]    at 0x........: main (isa_check.c:44)
	Address: 0x........	size: 8	state: FLUSHED
[1]    at 0x........: main (isa_check.c:50)
	Address: 0x........	size: 8	state: FLUSHED

Number of unnecessary flushes: 2
[0]    at 0x........: main (isa_check.c:39)
	Address: 0x........	size: 64
[1]    at 0x........: main (isa_check.c:41)
	Address: 0x........	size: 64
ERROR SUMMARY: 5 errors
