Number of stores not made persistent: 2
Stores not made persistent properly:
[0]    at 0x........: main (set_clean.c:30)
	Address: 0x........	size: 4	state: FLUSHED
[1]    at 0x........: main (set_clean.c:31)
	Address: 0x........	size: 4	state: DIRTY
Total memory not made persistent: 8
ERROR SUMMARY: 2 errors

Number of stores not made persistent: 1
Stores not made persistent properly:
[0]    at 0x........: main (set_clean.c:31)
	Address: 0x........	size: 2	state: DIRTY
Total memory not made persistent: 2
ERROR SUMMARY: 1 errors

Number of stores not made persistent: 0
ERROR SUMMARY: 0 errors

Number of stores not made persistent: 0
ERROR SUMMARY: 0 errors

