Number of stores not made persistent: 4
Stores not made persistent properly:
[0]    at 0x........: main (trans_expl.c:36)
	Address: 0x........	size: 1	state: DIRTY
[1]    at 0x........: main (trans_expl.c:37)
	Address: 0x........	size: 2	state: DIRTY
[2]    at 0x........: main (trans_expl.c:38)
	Address: 0x........	size: 4	state: DIRTY
[3]    at 0x........: main (trans_expl.c:43)
	Address: 0x........	size: 8	state: DIRTY
Total memory not made persistent: 15

Number of stores made without adding to transaction: 3
Stores made without adding to transactions:
[0]    at 0x........: main (trans_expl.c:36)
	Address: 0x........	size: 1
[1]    at 0x........: main (trans_expl.c:37)
	Address: 0x........	size: 2
[2]    at 0x........: main (trans_expl.c:39)
	Address: 0x........	size: 8
ERROR SUMMARY: 7 errors
