Number of stores not made persistent: 1
Stores not made persistent properly:
[0]    at 0x........: main (trans_no_pmem.c:33)
	Address: 0x........	size: 1	state: DIRTY
Total memory not made persistent: 1

Number of active transactions: 1
[0]    at 0x........: main (trans_no_pmem.c:27)
	tx_id: ...	 nesting: 1
ERROR SUMMARY: 2 errors

Number of stores not made persistent: 1
Stores not made persistent properly:
[0]    at 0x........: main (trans_no_pmem.c:41)
	Address: 0x........	size: 1	state: DIRTY
Total memory not made persistent: 1

Number of stores made without adding to transaction: 1
Stores made without adding to transactions:
[0]    at 0x........: main (trans_no_pmem.c:41)
	Address: 0x........	size: 1
ERROR SUMMARY: 2 errors
