Number of stores not made persistent: 4
Stores not made persistent properly:
[0]    at 0x........: main (trans_nest.c:39)
	Address: 0x........	size: 1	state: DIRTY
[1]    at 0x........: main (trans_nest.c:40)
	Address: 0x........	size: 2	state: DIRTY
[2]    at 0x........: main (trans_nest.c:41)
	Address: 0x........	size: 4	state: DIRTY
[3]    at 0x........: main (trans_nest.c:42)
	Address: 0x........	size: 8	state: DIRTY
Total memory not made persistent: 15

Number of stores made outside of transactions: 2
Stores made outside of transactions:
[0]    at 0x........: main (trans_nest.c:39)
	Address: 0x........	size: 1
[1]    at 0x........: main (trans_nest.c:42)
	Address: 0x........	size: 8

Number of active transactions: 1
[0]    at 0x........: main (trans_nest.c:32)
	tx_id: ...	 nesting: 1

Number of stores not made persistent: 4
Stores not made persistent properly:
[0]    at 0x........: main (trans_nest.c:39)
	Address: 0x........	size: 1	state: DIRTY
[1]    at 0x........: main (trans_nest.c:49)
	Address: 0x........	size: 2	state: DIRTY
[2]    at 0x........: main (trans_nest.c:41)
	Address: 0x........	size: 4	state: DIRTY
[3]    at 0x........: main (trans_nest.c:53)
	Address: 0x........	size: 8	state: DIRTY
Total memory not made persistent: 15

Number of stores made outside of transactions: 3
Stores made outside of transactions:
[0]    at 0x........: main (trans_nest.c:39)
	Address: 0x........	size: 1
[1]    at 0x........: main (trans_nest.c:42)
	Address: 0x........	size: 8
[2]    at 0x........: main (trans_nest.c:49)
	Address: 0x........	size: 2
